In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

In [41]:
print(tf.__version__)

2.0.0


In [7]:
dataset=tf.data.Dataset.range(10)
for val in dataset:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [19]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True) #drop_remainder will give windows of 5 
for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(),end=" ")
    print() 

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [40]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True) #drop_remainder will give windows of 5 
dataset=dataset.flat_map(lambda window:window.batch(5))
dataset=dataset.map(lambda window:(window[:-1],window[-1]))
dataset=dataset.shuffle(buffer_size=10)
dataset=dataset.batch(2).prefetch(1)
for x,y in dataset:
    print("x =",x.numpy())
    print("y =",y.numpy())

x = [[4 5 6 7]
 [0 1 2 3]]
y = [8 4]
x = [[5 6 7 8]
 [2 3 4 5]]
y = [9 6]
x = [[1 2 3 4]
 [3 4 5 6]]
y = [5 7]
